/*
 * SERWER TCP
 * TWORZY I UDOSTEPNIA DANE DO OBLICZEN
 * ODBIERA WYNIKI OD KLIENTA
 *
 * MUSI OBSLUGIWAC 10 POLACZEN JEDNOCZESNIE
 * ZA POMOCA SELECTA
 *
 * POWINNEN BYC ZREALIZOWANY NA GNIAZDACH BLOKUJACYCH
 *
 * DANE DO OBLICZEN - TWORZONE PRZEZ SERWER
 * FORMAT unit32_
 * zakres 0 - 65535
 * FUNKCJA GENERUJACA DANE
 * PODANA W OSOBNYM DOKUMENCIE
 * NALEZY WLACZYC DO KODU - WYWOLAC PRZY KAZDYM TWORZENIU
 * NOWEGO ZESTAWU DANYCH
 *
 * OBLICZYC ILOSC WYSTAPIEN BITOW
 * NA POSZCZEGOLNYCH POZYCJACH W WARTOSCIACH WYGENEROWANYCH PRZEZ
 * SERWER bity 0-15
 *
 * SERWER URUCHAMIANY Z PARAMETRAMI
 * <nr portu nasluchujacego>
 *
 *
 * OTWIERA GNIAZDO NASLUCHUJACE TCP NA NUMERZE PORTU Z PARAMETRU
 *
 * SERWER ODPOWIADA NA PAKIET A1 PAKIETEM B1 Z KOMENDA P ORAZ NUMEREM PORTU
 * LUB PAKIETEM B2 Z KOMENDA X -  BRAK NOWYCH DANYCH
 *
 * PRZED WYSLANIEM B1 SERWER OTWIERA GNIAZDKO NASLUCHUJACE NA PORCIE
 * BEDZIE WYLICZANE NA PODSTAWIE PORT_NASLUCHUJACY + 1 + NUMER_ZESTAWU_DANYCH
 *
 * SERWER PO KOMENDZIE E UZYJE BLOKU DANYCH W KOLEJNYM POLACZENIU
 *
 * SERWER PO OTRZYMANIU WYNIKU SPRAWDZA WARTOSCI Z OTRZYMANMI OD KLIENTA
 * WYPISUJE INFO CZY WYNIKI SIE ZGADZAJA
 *
 * PO WYNIKACH SERWER WYSYLA DO KLIENTA PAKIET B3 Z KOEMNDA D I KONCZY POLACZENIE
 */
